In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r"C:\Users\Ashutosh Thakur\Desktop\ML tuts\Dataset\SampleFile.csv")
df.head()

LotArea  MSSubClass
0     8450          60
1     9600          20
2    11250          60
3     9550          70
4    14260          60

In [3]:
# Absolute maximum scaling:

In [6]:
max_vals = np.max((df))
max_vals

LotArea       215245
MSSubClass       190
dtype: int64

In [7]:
((df - max_vals) / max_vals)

LotArea  MSSubClass
0    -0.960742   -0.684211
1    -0.955400   -0.894737
2    -0.947734   -0.684211
3    -0.955632   -0.631579
4    -0.933750   -0.684211
...        ...         ...
1455 -0.963219   -0.684211
1456 -0.938791   -0.894737
1457 -0.957992   -0.631579
1458 -0.954856   -0.894737
1459 -0.953834   -0.894737

[1460 rows x 2 columns]

In [8]:
# Min Max Scaling

In [13]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df_MinMax = scaler.fit_transform(df)
df_MinMax

array([[0.0334198 , 0.23529412],
       [0.03879502, 0.        ],
       [0.04650728, 0.23529412],
       ...,
       [0.03618687, 0.29411765],
       [0.03934189, 0.        ],
       [0.04037019, 0.        ]])

In [15]:
df_MinMax = pd.DataFrame(df_MinMax, columns = df.columns)
df_MinMax.head()

LotArea  MSSubClass
0  0.033420    0.235294
1  0.038795    0.000000
2  0.046507    0.235294
3  0.038561    0.294118
4  0.060576    0.235294

In [16]:
# Normalization

In [18]:
from sklearn.preprocessing import Normalizer
scaler = Normalizer()
df_Norm = scaler.fit_transform(df)
df_Norm

array([[0.99997479, 0.00710041],
       [0.99999783, 0.00208333],
       [0.99998578, 0.00533326],
       ...,
       [0.99997003, 0.00774142],
       [0.99999788, 0.00205824],
       [0.99999797, 0.00201268]])

In [19]:
df_Norm = pd.DataFrame(df_Norm , columns = df.columns)
df_Norm.head()

LotArea  MSSubClass
0  0.999975    0.007100
1  0.999998    0.002083
2  0.999986    0.005333
3  0.999973    0.007330
4  0.999991    0.004208

In [20]:
# Standardization

In [24]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df_Std = scaler.fit_transform(df)
df_Std

array([[-0.20714171,  0.07337496],
       [-0.09188637, -0.87256276],
       [ 0.07347998,  0.07337496],
       ...,
       [-0.14781027,  0.30985939],
       [-0.08016039, -0.87256276],
       [-0.05811155, -0.87256276]])

In [25]:
df_Std = pd.DataFrame(df_Std , columns = df.columns)
df_Std.head()

LotArea  MSSubClass
0 -0.207142    0.073375
1 -0.091886   -0.872563
2  0.073480    0.073375
3 -0.096897    0.309859
4  0.375148    0.073375

In [26]:
# Robust Scaling

In [27]:
from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()
df_rob = scaler.fit_transform(df)
df_rob

array([[-0.25407609,  0.2       ],
       [ 0.03001482, -0.6       ],
       [ 0.43762352,  0.2       ],
       ...,
       [-0.10783103,  0.4       ],
       [ 0.05891798, -0.6       ],
       [ 0.11326581, -0.6       ]])

In [29]:
df_rob = pd.DataFrame(df_rob, columns = df.columns)
df_rob.head()

LotArea  MSSubClass
0 -0.254076         0.2
1  0.030015        -0.6
2  0.437624         0.2
3  0.017663         0.4
4  1.181201         0.2

StandardScaler works well when the data is Normally distributed. StandardScaler and RobustScaling are robust to outliers. MinMaxScaler and Normalizer are sensitive to outliers